/* tslint:disable */
/* eslint-disable */
/**
 * room.proto
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface ProtobufAny {
    [key: string]: object | any;

    '@type'?: string;
}
export interface RpcStatus {
    'code'?: number;
    'message'?: string;
    'details'?: Array<ProtobufAny>;
}
export interface V1CreateRoomRequest {
    'userName'?: string;
    'userId'?: string;
}
export interface V1GetRoomResponse {
    'room'?: V1Room;
}
export interface V1Room {
    'roomId'?: string;
    'users'?: Array<V1User>;
}
export interface V1StandardResponse {
    'success'?: boolean;
    'message'?: string;
}
export interface V1User {
    'userName'?: string;
    'userId'?: string;
    'userImage'?: string;
}

/**
 * RoomServiceApi - axios parameter creator
 */
export const RoomServiceApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {V1CreateRoomRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceCreateRoom: async (body: V1CreateRoomRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'body' is not null or undefined
            assertParamExists('roomServiceCreateRoom', 'body', body)
            const localVarPath = `/api/v1/room/create`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(body, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceDeleteRoom: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('roomServiceDeleteRoom', 'roomId', roomId)
            const localVarPath = `/api/v1/room/delete/{roomId}`
                .replace(`{${"roomId"}}`, encodeURIComponent(String(roomId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary 投稿操作
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceGetRoom: async (roomId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'roomId' is not null or undefined
            assertParamExists('roomServiceGetRoom', 'roomId', roomId)
            const localVarPath = `/api/v1/room/{roomId}`
                .replace(`{${"roomId"}}`, encodeURIComponent(String(roomId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RoomServiceApi - functional programming interface
 */
export const RoomServiceApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RoomServiceApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {V1CreateRoomRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomServiceCreateRoom(body: V1CreateRoomRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1StandardResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomServiceCreateRoom(body, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomServiceApi.roomServiceCreateRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomServiceDeleteRoom(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1StandardResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomServiceDeleteRoom(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomServiceApi.roomServiceDeleteRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary 投稿操作
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async roomServiceGetRoom(roomId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<V1GetRoomResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.roomServiceGetRoom(roomId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RoomServiceApi.roomServiceGetRoom']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RoomServiceApi - factory interface
 */
export const RoomServiceApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RoomServiceApiFp(configuration)
    return {
        /**
         * 
         * @param {V1CreateRoomRequest} body 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceCreateRoom(body: V1CreateRoomRequest, options?: RawAxiosRequestConfig): AxiosPromise<V1StandardResponse> {
            return localVarFp.roomServiceCreateRoom(body, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceDeleteRoom(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<V1StandardResponse> {
            return localVarFp.roomServiceDeleteRoom(roomId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary 投稿操作
         * @param {string} roomId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        roomServiceGetRoom(roomId: string, options?: RawAxiosRequestConfig): AxiosPromise<V1GetRoomResponse> {
            return localVarFp.roomServiceGetRoom(roomId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RoomServiceApi - object-oriented interface
 */
export class RoomServiceApi extends BaseAPI {
    /**
     * 
     * @param {V1CreateRoomRequest} body 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomServiceCreateRoom(body: V1CreateRoomRequest, options?: RawAxiosRequestConfig) {
        return RoomServiceApiFp(this.configuration).roomServiceCreateRoom(body, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} roomId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomServiceDeleteRoom(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomServiceApiFp(this.configuration).roomServiceDeleteRoom(roomId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary 投稿操作
     * @param {string} roomId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public roomServiceGetRoom(roomId: string, options?: RawAxiosRequestConfig) {
        return RoomServiceApiFp(this.configuration).roomServiceGetRoom(roomId, options).then((request) => request(this.axios, this.basePath));
    }
}



